server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book/**
        filters:
        - RewritePath=/book/(?<path>.*), /$\{path}
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<path>.*), /$\{path}
      - id: purchase-service
        uri: lb://purchase-service
        predicates:
        - Path=/purchase/**
        filters:
        - RewritePath=/purchase/(?<path>.*), /$\{path}
